### ISSUE TITLE
What is client_id in test2.html

### ISSUE THREAD

**Issue by ghost** [cometchat-go/javascript-chat-sdk#1]
What is client_id in test2.html

**Comment by anantgarg** [comment]
Oops. It was `chat_appid`. I have made the correction. Thank you for pointing out. You can check it now.

**Comment by ghost** [comment]
Please Change it in your docs as well and bdw how to make voice and video calls ?

**Comment by anantgarg** [comment]
Have made the change in our Developer Documentation as well. Thank you for pointing out.

To make voice & video calls, once you add the code, CometChat will appear on the site page. Select a user and click on "Webcam" icon. If you need assistance, please contact our sales team at https://www.cometchat.com/contact and our team will be happy to demo CometChat for you.

**Comment by ghost** [comment]
Thank you so much.
