### ISSUE TITLE
Module not found: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by huy-lv** [cometchat-go/javascript-chat-sdk#3]
Hi, when i use "@cometchat-pro/chat": "1.6.0" in my package.json of reactjs project, i got following warning.
```
./node_modules/@cometchat-pro/chat/CometChat.js
Module not found: Can't resolve 'react-native' in '/home/travis/build/huy-lv/teachild-web/node_modules/@cometchat-pro/chat'
```
Project still works fine, but when i deploy with Travis CI, it throw error and stop. What should i do 

![image](https://user-images.githubusercontent.com/7688070/59566562-0417ca80-908c-11e9-99e3-42ad1295000b.png)

**Comment by anantgarg** [comment]
We will be releasing a permanent fix for this shortly. 

For now, you can bypass the warning by setting CI=false during build time.

**Comment by huy-lv** [comment]
Excuse me, can you tell me how to setting CI=false, im using Gitlab CI

**Comment by anantgarg** [comment]
You can use the latest SDK. This issue has been resolved.

**Comment by anantgarg** [comment]
You no longer need to set CI=false.
